# -*- coding: utf-8 -*-
"""weather website.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rbVMpdfCZJoTFmLOUEHsHEMHg8yvISe0
"""

pip install requests

import requests

# Define your API key and the base URL
API_KEY = 'fdbae4344e382c24cf2442f1456da6d6'
 # Replace with your OpenWeatherMap API key
BASE_URL = 'http://api.openweathermap.org/data/2.5/weather'

# Function to get weather data
def get_weather(city):
    # Build the complete API URL
    url = f"{BASE_URL}?q={city}&appid={API_KEY}&units=metric"  # Use 'imperial' for Fahrenheit
    response = requests.get(url)

    if response.status_code == 200:
        data = response.json()

        # Extract relevant information
        main = data['main']
        weather = data['weather'][0]
        temperature = main['temp']
        humidity = main['humidity']
        description = weather['description']

        # Print weather information
        print(f"City: {city}")
        print(f"Temperature: {temperature}°C")
        print(f"Humidity: {humidity}%")
        print(f"Weather: {description.capitalize()}")
    else:
        print("City not found. Please check the name.")

# Example usage
city_name = input("Enter city name: ")
get_weather(city_name)